version: "3.7"
services:
  db:
    image: "mongo"
    container_name: "MongoDB-Inventory-Manager"
    environment:
      - MONGO_INITDB_DATABASE=Inventory
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./datas:/data/db
    ports:
      - "27017-27019:27017-27019"
    restart: always
